### ISSUE TITLE
Defining minimum ORF length doesn't work

### ISSUE THREAD

**Issue by genomewalker** [soedinglab/plass#10]
Hi
when specifying a `--min-length` to the `assemble` workflow to set a minimum ORF length it is used as maximum length as seen [here](https://github.com/soedinglab/plass/blob/f30dfd9320d2f813a52bd7dd8e9951f4ee028518/src/workflow/Assembler.cpp#L139)

The output of the `extractorfs` workflow on commit 53a2eff54d26d24ec3c9486020ebf15add15af9f:
```
plass assemble tm8_1.truncated.fasta assembly.fas tmp --sub-mat PAM30.out --min-length 10
assemble tm8_1.truncated.fasta assembly.fas tmp --sub-mat PAM30.out --min-length 10
```

```
extractorfs /vol/attached/arctic/ORFs/tmp/18009091505483605488/nucl_reads /vol/attached/arctic/ORFs/tmp/18009091505483605488/nucl_6f_start --min-length 20 --max-length 10 --max-gaps 0 --contig-start-mode 1 --contig-end-mode 0 --orf-start-mode 0 --forward-frames 1,2,3 --reverse-frames 1,2,3 --translation-table 1 --use-all-table-starts 0 --id-offset 0 --threads 28 --compressed 0 -v 3
```

Thanks
Antonio

**Comment by martin-steinegger** [comment]
Thank you for reporting this. It should be fixed now.

**Comment by apcamargo** [comment]
I'm using the latest commit version and I think this problem persists (unless I'm interpreting the parameter wrong). My assemblies with default parameters (`--min-length` = 45) have many complete ORFs as short as 17 amino acids.
